Repository Young-N-Ambitious/yna_frontend, pull requests merged in 2022-10, with the labels that each got.

#3 Create LICENSE.md
  LICENSE.md
Labels: hacktoberfest-accepted

#4 FD-0009.2 Update Readme
  README.md
Labels: hacktoberfest-accepted

#6 FD-0091(docs)-Adds-contibutormd
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#15 FD-010 Stylization of Featured App: TailWind
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/index.css
  tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest

#17 FD-#7-feat:Routes added
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/aboutUs/AboutUs.js
  src/pages/contactUs/ContactUs.js
  src/pages/globalComponents/notFound/NotFound.js
  src/pages/homePage/HomePage.js
  src/pages/index.js
  src/pages/joinUs/JoinUs.js
  src/pages/login/login.js
  src/pages/members/Members.js
Labels: hacktoberfest-accepted, hacktoberfest

#22 FD-#11-test-RoutesTesting
  src/App.js
  src/App.test.js
  src/pages/aboutUs/AboutUs.js
  src/pages/contactUs/ContactUs.js
  src/pages/globalComponents/notFound/NotFound.js
  src/pages/homePage/HomePage.js
  src/pages/joinUs/JoinUs.js
  src/pages/login/login.js
  src/pages/members/Members.js
  src/test-utils.js
Labels: hacktoberfest-accepted, hacktoberfest

#24 Created Footer using Tailwind
  package-lock.json
  src/App.js
  src/assets/Linkedin.png
  src/assets/twitter.png
  src/pages/globalComponents/footer/Footer.js
Labels: hacktoberfest-accepted, hacktoberfest

#29 Updates Readme.md and Contributing.md
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#30 updated enviroment. Removed tailwind.
  package-lock.json
  package.json
  src/index.css
  tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest
